### ISSUE TITLE
not all data in "Get-WifiInfo" with a German OS

### ISSUE THREAD

**Issue by MrBiele** [vastlimits/uberAgent-Scripts#1]
unfortunately I can't get it to cleanly convert the value of "**Ü**bertragungsrate" to "Transmitrate" as well as the "**V**erschlüsselung" to "Cipher". The results always remain empty. 

Is there possibly an additional command, which outputs this via UTF8 or reasonable or the query results basically an English output, with a German operating system. 

Thanks for the script and hopefully a solution.

Best Regards

Sebastian

**Comment by martin-kretzschmar** [comment]
Hi Sebastian,

I changed the encoding for [Get-WifiInfoDe.ps1](https://github.com/vastlimits/uberAgent-Scripts/blob/main/Get-WifiInfo/Get-WifiInfoDe.ps1) to `UTF-8 with BOM`, which solves the issue for me.
Could you please double-check?

Thanks, Martin

**Comment by MrBiele** [comment]
Thanks Martin for the quick response!
Now it runs smoothly and I get all Data displayd! 

Best regards

Sebastian
