### ISSUE TITLE
Extension Install time

### ISSUE THREAD

**Issue by waydaws** [vastlimits/uberAgent-Scripts#2]
Running this manually shows ExtensionInstallTime="-11644473600000" which would seem to be 1600-12-31 16:00:00.000000.  That looks like the windows epoch time.  I'm wondering if it's something in the function ConvertChromeTimestampToEpochMs that is wrong, of if it's right and the browser extension does have that as install time.

**Comment by helgeklein** [comment]
Your question doesn't seem related to the scripts in this repo. Please contact our support at https://support.uberagent.com/ if you have questions related to the uberAgent browser extensions.
